### ISSUE TITLE
Where is the ui?

### ISSUE THREAD

**Issue by Jubilee101** [datamllab/autovideo#15]
Hi, in your demo video and your paper you mentioned this nice and fancy ui based on Orange. But I cannot seem to find it in the code. Can you point it to me? Also how do I bring up the ui after I install it? Thank you.

**Comment by daochenzha** [comment]
@Jubilee101 Thanks for the question. We have not open-sourced the GUI, as that part of the code is too messy. It requires considerable effort to make it ready. We do have some Orange code that will work for the D3M framework, but we did not properly maintain it. https://github.com/lhenry15/tods-gui

**Comment by Jubilee101** [comment]
I see, that helps too, thank you!
