### ISSUE TITLE
the project reuses some code from axolotl_tamu.

### ISSUE THREAD

**Issue by HuaizhengZhang** [datamllab/autovideo#2]
is this project open-source?
Or are there any documents?

**Comment by daochenzha** [comment]
@HuaizhengZhang Good question! The axolotl is a high-level abstraction of D3M with easier interfaces. axolotl_tamu is our maintained version of the axolotl. The original version is in https://gitlab.com/axolotl1/axolotl For this one, we are continuously adding new features so the code-base is not very stable. Thus, we maintain a stable and periodically updated version in https://github.com/tods-doc/axolotl This is the same one when you install axolotl_tamu
