### ISSUE TITLE
Running Predictions with pertained weights

### ISSUE THREAD

**Issue by nmochar2** [datamllab/autovideo#5]
Hi,

I'm trying to benchmark the hmdb51 and ucf101 datasets with the pertained weights available on Google Drive. I'm unfamiliar with axolotl library and am a little confused on how to populate fitted_pipeline['runtime'] if I don't try fitting using example/fit.py. Do you have any suggestions on how to accomplish this? 

Thank you,
Rohita

**Comment by daochenzha** [comment]
@nmochar2 Thanks for the feedback. We do not support this for now. I think the simplest solution is to just comment out this line https://github.com/datamllab/autovideo/blob/main/autovideo/base/supervised_base.py#L56 and run the fit with a pre-trained model. This will disable the training and directly save the model.

**Comment by nmochar2** [comment]
Thank you! I want to make sure I understand how the benchmark results were achieved https://github.com/datamllab/autovideo/blob/main/docs/benchmark.md . Were the pretrained weightsloaded and metrics were produced against the dataset or were the pretrained weights loaded and the network was finetuned with the dataset (e.i., ufc101 and hmdb51) and hyperparameters specified in the table?
